### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Arejula11/prompt_exit_status_bash_and_zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Arejula11** [comment]
Thank you for bringing up the issue. I've added a license to the project.
